로그인 화면 구성, 구글/카카오 로그인, 서버에서 accessToken 받아오기
boostcampwm2023/and07-MindSync pull request #149
Opened 2023-12-04 13:47 UTC by yang1318

## 관련 이슈
- #94 
- #95 
- #93 
## 작업한 내용
- 로그인 화면 구성
  <img width="251" alt="스크린샷 2023-12-04 오후 10 25 48" src="https://github.com/boostcampwm2023/and07-MindSync/assets/75965560/da4d7b99-ce03-40aa-9af3-11d5738b264b">  <img width="185" alt="스크린샷 2023-12-04 오후 10 25 58" src="https://github.com/boostcampwm2023/and07-MindSync/assets/75965560/63a0287f-6389-41f4-99b4-d57dba5373b5">
- 구글 로그인
- 카카오 로그인
- 카카오 로그인에서 받은 userId를 통해 Server에서 accessToken 받아옴
## To Reviewers
- 이 PR 머지된 후에 사용하시려면 local.properties에 kakaoClientId랑 Google Client Id가 필요합니당

2023-12-04 14:06 UTC, jaehan4707 requested changes

2023-12-04 14:06 UTC, jaehan4707 commented on AOS/app/src/main/res/layout/activity_login.xml
> +            android:text="마인드맵 작업은 MindSync!\n\n 3초 가입으로 간편하게 시작하세요"
string으로 바꿔주시와요

2023-12-04 14:06 UTC, jaehan4707 commented on AOS/app/src/main/java/boostcamp/and07/mindsync/ui/util/ExceptionMessage.kt
> +    ERROR_MESSAGE_CANT_GET_TOKEN("Can't get server access token"),
여기도 저희 Util에 Exception  있으니까 그걸로 하면 좋을거같아여

2023-12-04 14:06 UTC, jaehan4707 commented on AOS/app/src/main/res/layout/activity_login.xml
> +            android:onClick="kakaoSignInOnClick"
이거 이렇게 선언해도 클릭이벤트가 들어가나요?? 궁금해서요

2023-12-04 14:44 UTC, yang1318 commented on AOS/app/src/main/res/layout/activity_login.xml
> +            android:onClick="kakaoSignInOnClick"
넵 ㅎㅎ 대신 public 함수여야 해요!

2023-12-04 14:46 UTC, yang1318 commented on AOS/app/src/main/java/boostcamp/and07/mindsync/data/repository/login/LoginRepository.kt
> +//    fun loginWithGoogle()
아하 .. 생각해보니 불필요한 주석인 것 같아서 그냥 빼겠습니다!

2023-12-04 14:46 UTC, yang1318 commented on AOS/app/src/main/java/boostcamp/and07/mindsync/ui/util/ExceptionMessage.kt
> +    ERROR_MESSAGE_CANT_GET_TOKEN("Can't get server access token"),
ㅎㅎ이미 Exception에 있습니당~!ㅋㅋㅋㅋ

2023-12-05 01:52 UTC, jaehan4707 approved these changes

2023-12-05 01:55 UTC, hegleB approved these changes
수고하셨습니다 ~

2023-12-05 01:55 UTC, merged